### ISSUE TITLE
RobotoSerif variable font fails to outline

### ISSUE THREAD

**Issue by Xiphoseer** [harfbuzz/ttf-parser#186]
The [RobotoSerif 1.0](https://github.com/CommercialType/RobotoSerif/releases/tag/1.0) font seems to do something that causes the `outline_glyph` to stop working when the `variable-fonts` feature is enabled. A minimal case would be running

```rs
use ttf_parser::{Face, OutlineBuilder};

fn main() {
    let path = std::env::args().nth(1).expect("USAGE: varfont-test <file>");
    let data = std::fs::read(&path).expect("read file");
    let face = Face::parse(&data, 0).expect("parse face");

    let glyph_id = face.glyph_index('a').expect("glyph 'a'");
    face.outline_glyph(glyph_id, &mut Builder)
        .expect("outline_glyph");
}

struct Builder;
impl OutlineBuilder for Builder {
    fn move_to(&mut self, _x: f32, _y: f32) {}
    fn line_to(&mut self, _x: f32, _y: f32) {}
    fn quad_to(&mut self, _x1: f32, _y1: f32, _x: f32, _y: f32) {}
    fn curve_to(&mut self, _x1: f32, _y1: f32, _x2: f32, _y2: f32, _x: f32, _y: f32) {}
    fn close(&mut self) {}
}
```

with

```toml
[dependencies.ttf-parser]
version = "0.25.1"
default-features = false
features = ["opentype-layout", "std"]
```
vs.

```toml
[dependencies.ttf-parser]
version = "0.25.1"
default-features = false
features = ["opentype-layout", "std", "variable-fonts"]
```
